# Utilisation de l'image officielle de WordPress
FROM wordpress:latest

# Installation d'extensions ou de dépendances supplémentaires si nécessaire
RUN apt-get update && apt-get install -y \
    vim \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Variables d'environnement pour la connexion à la base de données
ENV WORDPRESS_DB_HOST=db \
    WORDPRESS_DB_USER=root \
    WORDPRESS_DB_PASSWORD=root \
    WORDPRESS_DB_NAME=mydatabase

# Exposer le port 80 pour le serveur web
EXPOSE 80





